name: Clear Cookies and Setup in Tor Browser

on:
  workflow_dispatch:

jobs:
  setup_tor_and_extensions:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Verify the actor triggering the workflow
      - name: Verify Triggering Actor
        id: check-actor
        run: |
          EXPECTED_ACTOR="kbongcawel-viatrm" # Replace with the correct actor username if needed
         